import shutil
from pathlib import Path

from setuptools import setup

# Remove stale exciton.egg-info directory to avoid
# https://github.com/pypa/pip/issues/5466
stale_egg_info = Path(__file__).parent / "raugen.egg-info"
if stale_egg_info.exists():
    print(
        (
            "Warning: {} exists.\n\n"
            "This directory is automatically generated by Python packaging tools.\n"
            "See https://github.com/pypa/pip/issues/5466 for details.\n"
        ).format(stale_egg_info)
    )
    shutil.rmtree(stale_egg_info)

dep_packages = []
with open("requirements.txt", "r") as fp:
    for line in fp:
        if line[0] != "#":
            dep_packages.append(str(line.strip()))

version = "0.0.5"

setup(
    name="raugen",
    version=version,
    keywords="AI Agents",
    description="A framework for designing and creating AI Agents",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    classifiers=[
        "Intended Audience :: AI Developers",
        "Development Status :: 3 - Alpha",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Topic :: Artificial Intelligence",
    ],
    url="https://github.com/yigerenwan/raugen",
    author="Yigerenwan",
    author_email="raugenai@gmail.com",
    package_dir={"": "."},
    package_data={".": ["*.txt"]},
    exclude_package_data={"raugen": ["research/*", "research/*/*"]},
    include_package_data=True,
    packages=["raugen"],
    install_requires=dep_packages,
    setup_requires=["pytest-runner"],
    python_requires=">=3.10",
    zip_safe=False,
)
